// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gms.proto

package gms

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType struct {
	CRC32                uint32   `protobuf:"varint,1,opt,name=CRC32,proto3" json:"CRC32,omitempty"`
	Magic                uint32   `protobuf:"varint,2,opt,name=Magic,proto3" json:"Magic,omitempty"`
	Attributes           uint32   `protobuf:"varint,3,opt,name=Attributes,proto3" json:"Attributes,omitempty"`
	KeyLength            uint64   `protobuf:"varint,4,opt,name=KeyLength,proto3" json:"KeyLength,omitempty"`
	KeyPayload           []byte   `protobuf:"bytes,5,opt,name=KeyPayload,proto3" json:"KeyPayload,omitempty"`
	ValueLength          uint64   `protobuf:"varint,6,opt,name=ValueLength,proto3" json:"ValueLength,omitempty"`
	ValuePayload         []byte   `protobuf:"bytes,7,opt,name=ValuePayload,proto3" json:"ValuePayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageType) Reset()         { *m = MessageType{} }
func (m *MessageType) String() string { return proto.CompactTextString(m) }
func (*MessageType) ProtoMessage()    {}
func (*MessageType) Descriptor() ([]byte, []int) {
	return fileDescriptor_57967f8871facd07, []int{0}
}

func (m *MessageType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageType.Unmarshal(m, b)
}
func (m *MessageType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageType.Marshal(b, m, deterministic)
}
func (m *MessageType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageType.Merge(m, src)
}
func (m *MessageType) XXX_Size() int {
	return xxx_messageInfo_MessageType.Size(m)
}
func (m *MessageType) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageType.DiscardUnknown(m)
}

var xxx_messageInfo_MessageType proto.InternalMessageInfo

func (m *MessageType) GetCRC32() uint32 {
	if m != nil {
		return m.CRC32
	}
	return 0
}

func (m *MessageType) GetMagic() uint32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *MessageType) GetAttributes() uint32 {
	if m != nil {
		return m.Attributes
	}
	return 0
}

func (m *MessageType) GetKeyLength() uint64 {
	if m != nil {
		return m.KeyLength
	}
	return 0
}

func (m *MessageType) GetKeyPayload() []byte {
	if m != nil {
		return m.KeyPayload
	}
	return nil
}

func (m *MessageType) GetValueLength() uint64 {
	if m != nil {
		return m.ValueLength
	}
	return 0
}

func (m *MessageType) GetValuePayload() []byte {
	if m != nil {
		return m.ValuePayload
	}
	return nil
}

type WriteMessageRequest struct {
	Partition            string         `protobuf:"bytes,1,opt,name=Partition,proto3" json:"Partition,omitempty"`
	TopicName            string         `protobuf:"bytes,2,opt,name=TopicName,proto3" json:"TopicName,omitempty"`
	Message              []*MessageType `protobuf:"bytes,3,rep,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *WriteMessageRequest) Reset()         { *m = WriteMessageRequest{} }
func (m *WriteMessageRequest) String() string { return proto.CompactTextString(m) }
func (*WriteMessageRequest) ProtoMessage()    {}
func (*WriteMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57967f8871facd07, []int{1}
}

func (m *WriteMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteMessageRequest.Unmarshal(m, b)
}
func (m *WriteMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteMessageRequest.Marshal(b, m, deterministic)
}
func (m *WriteMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteMessageRequest.Merge(m, src)
}
func (m *WriteMessageRequest) XXX_Size() int {
	return xxx_messageInfo_WriteMessageRequest.Size(m)
}
func (m *WriteMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteMessageRequest proto.InternalMessageInfo

func (m *WriteMessageRequest) GetPartition() string {
	if m != nil {
		return m.Partition
	}
	return ""
}

func (m *WriteMessageRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *WriteMessageRequest) GetMessage() []*MessageType {
	if m != nil {
		return m.Message
	}
	return nil
}

type WriteMessageResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Result               string   `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteMessageResponse) Reset()         { *m = WriteMessageResponse{} }
func (m *WriteMessageResponse) String() string { return proto.CompactTextString(m) }
func (*WriteMessageResponse) ProtoMessage()    {}
func (*WriteMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_57967f8871facd07, []int{2}
}

func (m *WriteMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteMessageResponse.Unmarshal(m, b)
}
func (m *WriteMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteMessageResponse.Marshal(b, m, deterministic)
}
func (m *WriteMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteMessageResponse.Merge(m, src)
}
func (m *WriteMessageResponse) XXX_Size() int {
	return xxx_messageInfo_WriteMessageResponse.Size(m)
}
func (m *WriteMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteMessageResponse proto.InternalMessageInfo

func (m *WriteMessageResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WriteMessageResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageType)(nil), "MessageType")
	proto.RegisterType((*WriteMessageRequest)(nil), "WriteMessageRequest")
	proto.RegisterType((*WriteMessageResponse)(nil), "WriteMessageResponse")
}

func init() { proto.RegisterFile("gms.proto", fileDescriptor_57967f8871facd07) }

var fileDescriptor_57967f8871facd07 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x6f, 0x83, 0x30,
	0x10, 0xc5, 0x4b, 0xc9, 0x1f, 0x71, 0xa4, 0x8b, 0x9b, 0x56, 0x56, 0x55, 0x55, 0x88, 0xa1, 0x62,
	0x62, 0x48, 0xd6, 0x2e, 0x2d, 0x43, 0x87, 0x94, 0x2a, 0x72, 0xa2, 0x76, 0x76, 0xc2, 0x89, 0x5a,
	0x02, 0x4c, 0xb1, 0x19, 0xf8, 0xb0, 0xfd, 0x2e, 0x15, 0x86, 0x08, 0x22, 0x65, 0xf3, 0xfb, 0x9d,
	0xee, 0x3d, 0x3f, 0x1b, 0x9c, 0x34, 0x57, 0x61, 0x59, 0x49, 0x2d, 0xfd, 0x3f, 0x0b, 0xdc, 0x18,
	0x95, 0xe2, 0x29, 0xee, 0x9b, 0x12, 0xc9, 0x12, 0xa6, 0x11, 0x8b, 0xd6, 0x2b, 0x6a, 0x79, 0x56,
	0x70, 0xc3, 0x3a, 0xd1, 0xd2, 0x98, 0xa7, 0xe2, 0x48, 0xaf, 0x3b, 0x6a, 0x04, 0x79, 0x02, 0x78,
	0xd5, 0xba, 0x12, 0x87, 0x5a, 0xa3, 0xa2, 0xb6, 0x19, 0x8d, 0x08, 0x79, 0x04, 0x67, 0x83, 0xcd,
	0x07, 0x16, 0xa9, 0xfe, 0xa1, 0x13, 0xcf, 0x0a, 0x26, 0x6c, 0x00, 0xed, 0xf6, 0x06, 0x9b, 0x2d,
	0x6f, 0x32, 0xc9, 0x13, 0x3a, 0xf5, 0xac, 0x60, 0xc1, 0x46, 0x84, 0x78, 0xe0, 0x7e, 0xf1, 0xac,
	0xc6, 0x7e, 0x7f, 0x66, 0xf6, 0xc7, 0x88, 0xf8, 0xb0, 0x30, 0xf2, 0xe4, 0x31, 0x37, 0x1e, 0x67,
	0xcc, 0x6f, 0xe0, 0xf6, 0xbb, 0x12, 0x1a, 0xfb, 0x8e, 0x0c, 0x7f, 0x6b, 0x54, 0xba, 0xbd, 0xda,
	0x96, 0x57, 0x5a, 0x68, 0x21, 0x0b, 0x53, 0xd5, 0x61, 0x03, 0x68, 0xa7, 0x7b, 0x59, 0x8a, 0xe3,
	0x27, 0xcf, 0xd1, 0x54, 0x76, 0xd8, 0x00, 0xc8, 0x33, 0xcc, 0xf3, 0xce, 0x8d, 0xda, 0x9e, 0x1d,
	0xb8, 0xab, 0x45, 0x38, 0x7a, 0x41, 0x76, 0x1a, 0xfa, 0x6f, 0xb0, 0x3c, 0x8f, 0x56, 0xa5, 0x2c,
	0x14, 0x12, 0x02, 0x93, 0x48, 0x26, 0x68, 0x62, 0xa7, 0xcc, 0x9c, 0xc9, 0x3d, 0xcc, 0x18, 0xaa,
	0x3a, 0xd3, 0x7d, 0x5c, 0xaf, 0x56, 0x11, 0xd8, 0xef, 0xf1, 0x8e, 0xbc, 0x80, 0xbb, 0xc3, 0x22,
	0xe9, 0x9d, 0xc8, 0x32, 0xbc, 0xd0, 0xe9, 0xe1, 0x2e, 0xbc, 0x14, 0xe7, 0x5f, 0x1d, 0x66, 0xe6,
	0xab, 0xd7, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x19, 0x54, 0xe8, 0xda, 0xf7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GMSClient is the client API for GMS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GMSClient interface {
	SendMessage(ctx context.Context, in *WriteMessageRequest, opts ...grpc.CallOption) (*WriteMessageResponse, error)
}

type gMSClient struct {
	cc *grpc.ClientConn
}

func NewGMSClient(cc *grpc.ClientConn) GMSClient {
	return &gMSClient{cc}
}

func (c *gMSClient) SendMessage(ctx context.Context, in *WriteMessageRequest, opts ...grpc.CallOption) (*WriteMessageResponse, error) {
	out := new(WriteMessageResponse)
	err := c.cc.Invoke(ctx, "/GMS/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GMSServer is the server API for GMS service.
type GMSServer interface {
	SendMessage(context.Context, *WriteMessageRequest) (*WriteMessageResponse, error)
}

func RegisterGMSServer(s *grpc.Server, srv GMSServer) {
	s.RegisterService(&_GMS_serviceDesc, srv)
}

func _GMS_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMSServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GMS/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMSServer).SendMessage(ctx, req.(*WriteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GMS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GMS",
	HandlerType: (*GMSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _GMS_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gms.proto",
}
